### ISSUE TITLE
完善需求文档

### ISSUE THREAD

**Issue by coredux** [coredux/oopassignment#1]
各成员，
       请阅读需求文档，结合盲审系统的文档，审查一下各个用例，如果用例准确，则可进行下一步工作，我会分配需求文档的任务，这段时间大家先看一看PPT，并且请不熟悉github的同学熟悉一下github，周日再进行下一步的工作安排。

**Comment by yichenluan** [comment]
收到

**Comment by coredux** [comment]
1.用例图已更新，上传论文变成研究生自己的事，办公室管理人员只负责查相似度录结果
2.研究生导师这个角色在我看来并没有什么用，我觉得可以完全替换成专家，诸位怎么看

**Comment by yichenluan** [comment]
Re 2： 研究生导师只是线下部分才存在的，咱们线上系统一开始的入口就是研究生提交论文，这个时候论文已经经过导师签字了，所以，我觉得直接可以忽略研究生导师这个角色。

**Comment by Sunny8567** [comment]
收到

**Comment by coredux** [comment]
如果咱们都觉得可以把导师忽略掉，用专家来代替，那用例图基本没有什么改动，二者只是名字不一样，因为我用例图里面画的就是导师负责审查论文。
如果没有什么问题，大家可以看看图3-1和图3-2，明天咱们直接开始设计类好了
